configfile: "./config.yaml"

# set folder structure
MAIN_DIR   = config['main_dir']
DATA_DIR   = config['data_dir']

SCRIPT_DIR = config['main_dir'] + '/scripts'
SNAKE_DIR  = config['main_dir'] + '/snakes'

# set parameters
DATABASES = config['databases']
CLUSTER_METHODS = config['cluster_method']
TYPE = config['type']

THREADS = config['threads']
VARIANCE_THRESHOLD = config['variance_threshold']

# if HOSTS = '' , TRAIN_NUM should be bigger than 1
# next line generated by: less 004_hosts.counts | head -n 15 | grep -v no_host | sed 's/\s.*\s//' | tr '\n' ',' | less
# TODO: code set_hosts()
# HOSTS = set_hosts(config['hosts'], config['train_num'])
TRAIN_NUM = config['train_num']
TRAIN_PERCENTAGE = config['train_perc']

# pipeline will do annotation of these clusters using interproscan
CLUSTERS = []
# next line generated by: less 006_test.genomes.fasta | grep "^>" | tr -d '>' | tr '\n' ',' | less
PHAGES = ''



rule retrieve_data:
  input:
    expand(['{data_dir}/003_deduplicated.genomes.fasta', '{data_dir}/004_genera.tsv'],
            data_dir=DATA_DIR,
            ),

#rule analyse_data:
#  input:
#    '{data_dir}/013_models.{clustermethod}.{type}.completed',
#
#rule evaluate_models:
#  input:
#    expand('{data_dir}/015_{set_name}_{cluster_method}.{type}.{spec}.stats',
#            data_dir=DATA_DIR,
#            set_name='test',
#            cluster_method=CLUSTER_METHODS,
#            type=TYPE,
#            spec=HOSTS.split(',')),
#
#rule annotate_clusters:
#  input:
#    expand('{data_dir}/011_{cluster_method}_cluster_annotations/Cluster_{i}.result',
#            data_dir=DATA_DIR,
#            cluster_method=CLUSTER_METHODS,
#            i=CLUSTERS),

include: '{snake_dir}/retrieve_data.snake'.format(snake_dir=SNAKE_DIR)
include: '{snake_dir}/rules.snake'.format(snake_dir=SNAKE_DIR)
